name: bsync.build
on:
- push

jobs:
  build-xmit:
    name: Build transmitter
    runs-on: ubuntu-20.04 # 20.04 required for `llvm-strip`
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install system dependencies
        run: sudo apt install musl-tools llvm lld
      - name: Add targets
        run: rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl
      - name: Build
        run: |
          cd bsync-transmit
          cargo build --release --target x86_64-unknown-linux-musl
          cargo build --release --target aarch64-unknown-linux-musl
          mkdir dist
          cp ../target/x86_64-unknown-linux-musl/release/bsync-transmit ./dist/bsync-transmit.x86_64-unknown-linux-musl
          cp ../target/aarch64-unknown-linux-musl/release/bsync-transmit ./dist/bsync-transmit.aarch64-unknown-linux-musl
          llvm-strip ./dist/*
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: transmitter
          path: ./bsync-transmit/dist
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-18.04
    needs: build-xmit
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch transmitter
        uses: actions/download-artifact@v2
        with:
          name: transmitter
          path: ./bsync/bsync-transmit-dist
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Build
        run: |
          cd bsync
          cargo build --release
          cargo deb --no-strip
          cd ..
          mkdir deb-dist bin-dist
          cp target/debian/*.deb ./deb-dist/
          cp target/release/bsync ./bin-dist/
      - name: Upload deb-dist
        uses: actions/upload-artifact@v2
        with:
          name: debian-package
          path: ./deb-dist
      - name: Upload bin-dist
        uses: actions/upload-artifact@v2
        with:
          name: linux-binary
          path: ./bin-dist
  build-macos:
    name: Build (macOS)
    runs-on: macos-10.15
    needs: build-xmit
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch transmitter
        uses: actions/download-artifact@v2
        with:
          name: transmitter
          path: ./bsync/bsync-transmit-dist
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build
        run: |
          cd bsync
          cargo build --release
          cd ..
          mkdir bin-dist
          cp target/release/bsync ./bin-dist/
      - name: Upload bin-dist
        uses: actions/upload-artifact@v2
        with:
          name: macos-binary
          path: ./bin-dist
  build-freebsd:
    name: Build (FreeBSD)
    runs-on: macos-10.15
    needs: build-xmit
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch transmitter
        uses: actions/download-artifact@v2
        with:
          name: transmitter
          path: ./bsync/bsync-transmit-dist
      - name: Build
        uses: vmactions/freebsd-vm@v0.1.5
        with:
          usesh: true
          prepare: |
            pkg install -y curl
            curl https://sh.rustup.rs -sSf | sh -s -- -y
          run: |
            pwd
            ls -lah
            whoami
            env
            freebsd-version
            cd bsync
            cargo build --release
            cd ..
            mkdir bin-dist
            cp ./target/release/bsync ./bin-dist/
      - name: Upload bin-dist
        uses: actions/upload-artifact@v2
        with:
          name: freebsd-binary
          path: ./bin-dist
