name: blkredo.build
on:
- push

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install system dependencies
        run: sudo apt install musl-tools llvm-tools lld
      - name: Add targets
        run: rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl
      - name: Build
        run: ./build.sh
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: exe-linux
          path: target/release/blkredo
