name: bsync.build
on:
- push

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install system dependencies
        run: sudo apt install musl-tools llvm lld
      - name: Add targets
        run: rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl
      - name: Build
        run: ./build.sh
      - name: Build static
        run: cd bsync && cargo build --release --target x86_64-unknown-linux-musl --features vendored
      - name: Collect binaries
        run: |
          mkdir dist
          cp ./target/release/bsync ./dist/bsync.x86_64-unknown-linux-gnu
          cp ./target/x86_64-unknown-linux-musl/release/bsync ./dist/bsync.x86_64-unknown-linux-musl
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: exe-linux
          path: ./dist
